import 'package:sudan_horizon_scanner/imports.dart';

List<String> typeOfClusters = [
  "Agriculture",
  "Conflict",
  "Economic",
  "Education",
  "Environment",
  "Food Security and Nutrition",
  "Gender",
  "Health",
  "Infrastructure",
  "Population",
  "Poverty",
];

List<String> agricultureIndicators = [
  'crop and stock Production, area and yield ',
  'Production indecies (gross production and gross per capita)'
];

List<String> conflictIndicators = [
  'Conflict events, actors, fatalities',
  'Peace agreements, '
];

List<String> economicIndicators = [
  "Adjusted net national income (annual % growth)",
  "Adjusted net national income (current US\$)",
  "Adjusted net national income per capita (annual % growth)",
  "Adjusted net national income per capita (current US\$)",
  "Adjusted net savings, excluding particulate emission damage (% of GNI)",
  "Adjusted net savings, excluding particulate emission damage (current US\$)",
  "Adjusted net savings, including particulate emission damage (% of GNI)",
  "Adjusted net savings, including particulate emission damage (current US\$)",
  "Adjusted savings: carbon dioxide damage (% of GNI)",
  "Adjusted savings: carbon dioxide damage (current US\$)",
  "Adjusted savings: consumption of fixed capital (% of GNI)",
  "Adjusted savings: consumption of fixed capital (current US\$)",
  "Adjusted savings: education expenditure (% of GNI)",
  "Adjusted savings: education expenditure (current US\$)",
  "Adjusted savings: energy depletion (% of GNI)",
  "Adjusted savings: energy depletion (current US\$)",
  "Adjusted savings: gross savings (% of GNI)",
  "Adjusted savings: mineral depletion (% of GNI)",
  "Adjusted savings: mineral depletion (current US\$)",
  "Adjusted savings: natural resources depletion (% of GNI)",
  "Adjusted savings: net forest depletion (% of GNI)",
  "Adjusted savings: net forest depletion (current US\$)",
  "Adjusted savings: net national savings (% of GNI)",
  "Adjusted savings: net national savings (current US\$)",
  "Adjusted savings: particulate emission damage (% of GNI)",
  "Adjusted savings: particulate emission damage (current US\$)",
  "Agriculture, forestry, and fishing, value added (% of GDP)",
  "Agriculture, forestry, and fishing, value added (annual % growth)",
  "Agriculture, forestry, and fishing, value added (constant 2010 US\$)",
  "Agriculture, forestry, and fishing, value added (constant LCU)",
  "Agriculture, forestry, and fishing, value added (current LCU)",
  "Agriculture, forestry, and fishing, value added (current US\$)",
  "Agriculture, forestry, and fishing, value added per worker (constant 2010 US\$)",
  "Changes in inventories (constant LCU)",
  "Changes in inventories (current LCU)",
  "Changes in inventories (current US\$)",
  "Charges for the use of intellectual property, payments (BoP, current US\$)",
  "Charges for the use of intellectual property, receipts (BoP, current US\$)",
  "Chemicals (% of value added in manufacturing)",
  "Commercial banks and other lending (PPG + PNG) (NFL, current US\$)",
  "Communications, computer, etc. (% of service exports, BoP)",
  "Communications, computer, etc. (% of service imports, BoP)",
  "Current account balance (% of GDP)",
  "Current account balance (BoP, current US\$)",
  "Debt service (PPG and IMF only, % of exports of goods, services and primary income)",
  "Debt service on external debt, public and publicly guaranteed (PPG) (TDS, current US\$)",
  "Debt service on external debt, total (TDS, current US\$)",
  "Discrepancy in expenditure estimate of GDP (constant LCU)",
  "Discrepancy in expenditure estimate of GDP (current LCU)",
  "Exports as a capacity to import (constant LCU)",
  "Exports of goods and services (% of GDP)",
  "Exports of goods and services (annual % growth)",
  "Exports of goods and services (BoP, current US\$)",
  "Exports of goods and services (constant 2010 US\$)",
  "Exports of goods and services (constant LCU)",
  "Exports of goods and services (current LCU)",
  "Exports of goods and services (current US\$)",
  "Exports of goods, services and primary income (BoP, current US\$)",
  "External balance on goods and services (% of GDP)",
  "External balance on goods and services (constant LCU)",
  "External balance on goods and services (current LCU)",
  "External balance on goods and services (current US\$)",
  "External debt stocks (% of GNI)",
  "External debt stocks, long-term (DOD, current US\$)",
  "External debt stocks, private nonguaranteed (PNG) (DOD, current US\$)",
  "External debt stocks, public and publicly guaranteed (PPG) (DOD, current US\$)",
  "External debt stocks, short-term (DOD, current US\$)",
  "External debt stocks, total (DOD, current US\$)",
  "Final consumption expenditure (% of GDP)",
  "Final consumption expenditure (annual % growth)",
  "Final consumption expenditure (constant 2010 US\$)",
  "Final consumption expenditure (constant LCU)",
  "Final consumption expenditure (current LCU)",
  "Final consumption expenditure (current US\$)",
  "Food, beverages and tobacco (% of value added in manufacturing)",
  "Foreign direct investment, net (BoP, current US\$)",
  "Foreign direct investment, net inflows (% of GDP)",
  "Foreign direct investment, net inflows (BoP, current US\$)",
  "Foreign direct investment, net outflows (% of GDP)",
  "Foreign direct investment, net outflows (BoP, current US\$)",
  "GDP (constant 2010 US\$)",
  "GDP (constant LCU)",
  "GDP (current LCU)",
  "GDP (current US\$)",
  "GDP growth (annual %)",
  "GDP per capita (constant 2010 US\$)",
  "GDP per capita (constant LCU)",
  "GDP per capita (current LCU)",
  "GDP per capita (current US\$)",
  "GDP per capita growth (annual %)",
  "GDP per capita, PPP (constant 2017 international \$)",
  "GDP per capita, PPP (current international \$)",
  "GDP, PPP (constant 2017 international \$)",
  "GDP, PPP (current international \$)",
  "GDP: linked series (current LCU)",
  "General government final consumption expenditure (% of GDP)",
  "General government final consumption expenditure (annual % growth)",
  "General government final consumption expenditure (constant 2010 US\$)",
  "General government final consumption expenditure (constant LCU)",
  "General government final consumption expenditure (current LCU)",
  "General government final consumption expenditure (current US\$)",
  "GNI (constant 2010 US\$)",
  "GNI (constant LCU)",
  "GNI (current LCU)",
  "GNI (current US\$)",
  "GNI growth (annual %)",
  "GNI per capita (constant 2010 US\$)",
  "GNI per capita (constant LCU)",
  "GNI per capita (current LCU)",
  "GNI per capita growth (annual %)",
  "GNI per capita, Atlas method (current US\$)",
  "GNI per capita, PPP (constant 2017 international \$)",
  "GNI per capita, PPP (current international \$)",
  "GNI, Atlas method (current US\$)",
  "GNI, PPP (constant 2017 international \$)",
  "GNI, PPP (current international \$)",
  "GNI: linked series (current LCU)",
  "Goods exports (BoP, current US\$)",
  "Goods imports (BoP, current US\$)",
  "Grants, excluding technical cooperation (BoP, current US\$)",
  "Gross capital formation (% of GDP)",
  "Gross capital formation (annual % growth)",
  "Gross capital formation (constant 2010 US\$)",
  "Gross capital formation (constant LCU)",
  "Gross capital formation (current LCU)",
  "Gross capital formation (current US\$)",
  "Gross domestic income (constant LCU)",
  "Gross domestic savings (% of GDP)",
  "Gross domestic savings (current LCU)",
  "Gross domestic savings (current US\$)",
  "Gross fixed capital formation (% of GDP)",
  "Gross fixed capital formation (annual % growth)",
  "Gross fixed capital formation (constant 2010 US\$)",
  "Gross fixed capital formation (constant LCU)",
  "Gross fixed capital formation (current LCU)",
  "Gross fixed capital formation (current US\$)",
  "Gross fixed capital formation, private sector (% of GDP)",
  "Gross fixed capital formation, private sector (current LCU)",
  "Gross national expenditure (% of GDP)",
  "Gross national expenditure (constant 2010 US\$)",
  "Gross national expenditure (constant LCU)",
  "Gross national expenditure (current LCU)",
  "Gross national expenditure (current US\$)",
  "Gross national expenditure deflator (base year varies by country)",
  "Gross savings (% of GDP)",
  "Gross savings (% of GNI)",
  "Gross savings (current LCU)",
  "Gross savings (current US\$)",
  "Gross value added at basic prices (GVA) (constant 2010 US\$)",
  "Gross value added at basic prices (GVA) (constant LCU)",
  "Gross value added at basic prices (GVA) (current LCU)",
  "Gross value added at basic prices (GVA) (current US\$)",
  "Households and NPISHs final consumption expenditure (% of GDP)",
  "Households and NPISHs Final consumption expenditure (annual % growth)",
  "Households and NPISHs Final consumption expenditure (constant 2010 US\$)",
  "Households and NPISHs Final consumption expenditure (constant LCU)",
  "Households and NPISHs Final consumption expenditure (current LCU)",
  "Households and NPISHs Final consumption expenditure (current US\$)",
  "Households and NPISHs Final consumption expenditure per capita (constant 2010 US\$)",
  "Households and NPISHs Final consumption expenditure per capita growth (annual %)",
  "Households and NPISHs Final consumption expenditure, PPP (constant 2017 international \$)",
  "Households and NPISHs Final consumption expenditure, PPP (current international \$)",
  "Households and NPISHs final consumption expenditure: linked series (current LCU)",
  "IBRD loans and IDA credits (DOD, current US\$)",
  "IFC, private nonguaranteed (NFL, current US\$)",
  "IMF repurchases and charges (TDS, current US\$)",
  "Imports of goods and services (% of GDP)",
  "Imports of goods and services (annual % growth)",
  "Imports of goods and services (BoP, current US\$)",
  "Imports of goods and services (constant 2010 US\$)",
  "Imports of goods and services (constant LCU)",
  "Imports of goods and services (current LCU)",
  "Imports of goods and services (current US\$)",
  "Imports of goods, services and primary income (BoP, current US\$)",
  "Industry (including construction), value added (% of GDP)",
  "Industry (including construction), value added (annual % growth)",
  "Industry (including construction), value added (constant 2010 US\$)",
  "Industry (including construction), value added (constant LCU)",
  "Industry (including construction), value added (current LCU)",
  "Industry (including construction), value added (current US\$)",
  "Industry (including construction), value added per worker (constant 2010 US\$)",
  "Insurance and financial services (% of service exports, BoP)",
  "Insurance and financial services (% of service imports, BoP)",
  "Machinery and transport equipment (% of value added in manufacturing)",
  "Manufacturing, value added (% of GDP)",
  "Manufacturing, value added (annual % growth)",
  "Manufacturing, value added (constant LCU)",
  "Manufacturing, value added (current LCU)",
  "Manufacturing, value added (current US\$)",
  "Multilateral debt service (% of public and publicly guaranteed debt service)",
  "Multilateral debt service (TDS, current US\$)",
  "Net bilateral aid flows from DAC donors, Australia (current US\$)",
  "Net bilateral aid flows from DAC donors, Austria (current US\$)",
  "Net bilateral aid flows from DAC donors, Belgium (current US\$)",
  "Net bilateral aid flows from DAC donors, Canada (current US\$)",
  "Net bilateral aid flows from DAC donors, Czech Republic (current US\$)",
  "Net bilateral aid flows from DAC donors, Denmark (current US\$)",
  "Net bilateral aid flows from DAC donors, European Union institutions (current US\$)",
  "Net bilateral aid flows from DAC donors, Finland (current US\$)",
  "Net bilateral aid flows from DAC donors, France (current US\$)",
  "Net bilateral aid flows from DAC donors, Germany (current US\$)",
  "Net bilateral aid flows from DAC donors, Greece (current US\$)",
  "Net bilateral aid flows from DAC donors, Hungary (current US\$)",
  "Net bilateral aid flows from DAC donors, Iceland (current US\$)",
  "Net bilateral aid flows from DAC donors, Ireland (current US\$)",
  "Net bilateral aid flows from DAC donors, Italy (current US\$)",
  "Net bilateral aid flows from DAC donors, Japan (current US\$)",
  "Net bilateral aid flows from DAC donors, Korea, Rep. (current US\$)",
  "Net bilateral aid flows from DAC donors, Luxembourg (current US\$)",
  "Net bilateral aid flows from DAC donors, Netherlands (current US\$)",
  "Net bilateral aid flows from DAC donors, New Zealand (current US\$)",
  "Net bilateral aid flows from DAC donors, Norway (current US\$)",
  "Net bilateral aid flows from DAC donors, Poland (current US\$)",
  "Net bilateral aid flows from DAC donors, Portugal (current US\$)",
  "Net bilateral aid flows from DAC donors, Slovak Republic (current US\$)",
  "Net bilateral aid flows from DAC donors, Slovenia (current US\$)",
  "Net bilateral aid flows from DAC donors, Spain (current US\$)",
  "Net bilateral aid flows from DAC donors, Sweden (current US\$)",
  "Net bilateral aid flows from DAC donors, Switzerland (current US\$)",
  "Net bilateral aid flows from DAC donors, Total (current US\$)",
  "Net bilateral aid flows from DAC donors, United Kingdom (current US\$)",
  "Net bilateral aid flows from DAC donors, United States (current US\$)",
  "Net capital account (BoP, current US\$)",
  "Net errors and omissions (BoP, current US\$)",
  "Net financial account (BoP, current US\$)",
  "Net financial flows, bilateral (NFL, current US\$)",
  "Net financial flows, IBRD (NFL, current US\$)",
  "Net financial flows, IDA (NFL, current US\$)",
  "Net financial flows, IMF concessional (NFL, current US\$)",
  "Net financial flows, IMF nonconcessional (NFL, current US\$)",
  "Net financial flows, multilateral (NFL, current US\$)",
  "Net financial flows, others (NFL, current US\$)",
  "Net financial flows, RDB concessional (NFL, current US\$)",
  "Net financial flows, RDB nonconcessional (NFL, current US\$)",
  "Net flows on external debt, private nonguaranteed (PNG) (NFL, current US\$)",
  "Net ODA provided to the least developed countries (% of GNI)",
  "Net ODA provided, to the least developed countries (current US\$)",
  "Net ODA provided, total (% of GNI)",
  "Net ODA provided, total (constant 2015 US\$)",
  "Net ODA provided, total (current US\$)",
  "Net ODA received (% of central government expense)",
  "Net ODA received (% of GNI)",
  "Net ODA received (% of gross capital formation)",
  "Net ODA received (% of imports of goods, services and primary income)",
  "Net ODA received per capita (current US\$)",
  "Net official aid received (constant 2018 US\$)",
  "Net official aid received (current US\$)",
  "Net official development assistance and official aid received (constant 2018 US\$)",
  "Net official development assistance and official aid received (current US\$)",
  "Net official development assistance received (constant 2018 US\$)",
  "Net official development assistance received (current US\$)",
  "Net official flows from UN agencies, FAO (current US\$)",
  "Net official flows from UN agencies, IAEA (current US\$)",
  "Net official flows from UN agencies, IFAD (current US\$)",
  "Net official flows from UN agencies, ILO (current US\$)",
  "Net official flows from UN agencies, UNAIDS (current US\$)",
  "Net official flows from UN agencies, UNDP (current US\$)",
  "Net official flows from UN agencies, UNECE (current US\$)",
  "Net official flows from UN agencies, UNEP (current US\$)",
  "Net official flows from UN agencies, UNFPA (current US\$)",
  "Net official flows from UN agencies, UNHCR (current US\$)",
  "Net official flows from UN agencies, UNICEF (current US\$)",
  "Net official flows from UN agencies, UNIDIR (current US\$)",
  "Net official flows from UN agencies, UNPBF (current US\$)",
  "Net official flows from UN agencies, UNRWA (current US\$)",
  "Net official flows from UN agencies, UNTA (current US\$)",
  "Net official flows from UN agencies, UNWTO (current US\$)",
  "Net official flows from UN agencies, WFP (current US\$)",
  "Net official flows from UN agencies, WHO (current US\$)",
  "Net primary income (BoP, current US\$)",
  "Net primary income (Net income from abroad) (current LCU)",
  "Net primary income (Net income from abroad) (current US\$)",
  "Net secondary income (BoP, current US\$)",
  "Net secondary income (Net current transfers from abroad) (constant LCU)",
  "Net secondary income (Net current transfers from abroad) (current LCU)",
  "Net secondary income (Net current transfers from abroad) (current US\$)",
  "Net trade in goods (BoP, current US\$)",
  "Net trade in goods and services (BoP, current US\$)",
  "Other manufacturing (% of value added in manufacturing)",
  "Personal remittances, paid (current US\$)",
  "Personal remittances, received (% of GDP)",
  "Personal remittances, received (current US\$)",
  "Personal transfers, receipts (BoP, current US\$)",
  "Portfolio equity, net inflows (BoP, current US\$)",
  "Portfolio investment, bonds (PPG + PNG) (NFL, current US\$)",
  "Portfolio investment, net (BoP, current US\$)",
  "PPG, bonds (NFL, current US\$)",
  "PPG, commercial banks (NFL, current US\$)",
  "PPG, IBRD (DOD, current US\$)",
  "PPG, IDA (DOD, current US\$)",
  "PPG, official creditors (NFL, current US\$)",
  "PPG, other private creditors (NFL, current US\$)",
  "PPG, private creditors (NFL, current US\$)",
  "PPP conversion factor, GDP (LCU per international \$)",
  "PPP conversion factor, private consumption (LCU per international \$)",
  "Price level ratio of PPP conversion factor (GDP) to market exchange rate",
  "Primary income payments (BoP, current US\$)",
  "Primary income receipts (BoP, current US\$)",
  "Public and publicly guaranteed debt service (% of exports of goods, services and primary income)",
  "Public and publicly guaranteed debt service (% of GNI)",
  "Reserves and related items (BoP, current US\$)",
  "Secondary income receipts (BoP, current US\$)",
  "Secondary income, other sectors, payments (BoP, current US\$)",
  "Service exports (BoP, current US\$)",
  "Service imports (BoP, current US\$)",
  "Services, value added (% of GDP)",
  "Services, value added (annual % growth)",
  "Services, value added (constant 2010 US\$)",
  "Services, value added (constant LCU)",
  "Services, value added (current LCU)",
  "Services, value added (current US\$)",
  "Services, value added per worker (constant 2010 US\$)",
  "Short-term debt (% of exports of goods, services and primary income)",
  "Short-term debt (% of total external debt)",
  "Short-term debt (% of total reserves)",
  "Taxes less subsidies on products (constant LCU)",
  "Taxes less subsidies on products (current LCU)",
  "Taxes less subsidies on products (current US\$)",
  "Technical cooperation grants (BoP, current US\$)",
  "Terms of trade adjustment (constant LCU)",
  "Textiles and clothing (% of value added in manufacturing)",
  "Total debt service (% of exports of goods, services and primary income)",
  "Total debt service (% of GNI)",
  "Total reserves (% of total external debt)",
  "Total reserves (includes gold, current US\$)",
  "Total reserves in months of imports",
  "Total reserves minus gold (current US\$)",
  "Trade (% of GDP)",
  "Trade in services (% of GDP)",
  "Transport services (% of service exports, BoP)",
  "Transport services (% of service imports, BoP)",
  "Travel services (% of service exports, BoP)",
  "Travel services (% of service imports, BoP)",
  "Use of IMF credit (DOD, current US\$)"
];

List<String> educationIndicators = [];

List<String> environmentIndicators = [
  'Natural disasters and subgroups',
  'Mean temp',
  'Mean rain fall',
  'Mean temp projected (4 scenarios based on emmition levels)',
  'Mean rain fall (4 scenarios based on emmition levels)',
  'Projection of agricutural and drought indicators (4 scenarios based on emmition levels)',
  'Protected areas',
  'Potencial for wind energy (map)',
  'Potencial for solar energy (map)'
];

List<String> foodSecurityAndNutritionIndicators = [
  'Phase clasification per area',
  'Count of pop in phase 1',
  'Count of pop in phase 2',
  'Count of pop in phase 3',
  'Precentage of pop in phase 1',
  'Precentage of pop in phase 2',
  'Precentage of pop in phase 3',
  'Count of pop in phase 3+',
  'Precentage of pop in phase 3+',
  'Prevalence of anemia among children (% of children ages 6-59 months)',
  'Prevalence of anemia among non-pregnant women (% of women ages 15-49)',
  'Prevalence of anemia among pregnant women (%)',
  'Prevalence of anemia among women of reproductive age (% of women ages 15-49)',
  'Prevalence of overweight (% of children under 5)',
  'Prevalence of overweight (modeled estimate, % of children under 5)',
  'Prevalence of overweight, female (% of children under 5)',
  'Prevalence of overweight, male (% of children under 5)',
  'Prevalence of severe wasting, weight for height (% of children under 5)',
  'Prevalence of severe wasting, weight for height, female (% of children under 5)',
  'Prevalence of severe wasting, weight for height, male (% of children under 5)',
  'Prevalence of stunting, height for age (% of children under 5)',
  'Prevalence of stunting, height for age (modeled estimate, % of children under 5)',
  'Prevalence of stunting, height for age, female (% of children under 5)',
  'Prevalence of stunting, height for age, male (% of children under 5)',
  'Prevalence of undernourishment (% of population)',
  'Prevalence of underweight, weight for age (% of children under 5)',
  'Prevalence of underweight, weight for age, female (% of children under 5)',
  'Prevalence of underweight, weight for age, male (% of children under 5)',
  'Prevalence of wasting, weight for height (% of children under 5)',
  'Prevalence of wasting, weight for height, female (% of children under 5)',
  'Prevalence of wasting, weight for height, male (% of children under 5)'
];

List<String> genderIndicators = [
  'Ratio of female to male labor force participation rate (%) (modeled ILO estimate)',
  'A woman can apply for a passport in the same way as a man (1=yes; 0=no)',
  'A woman can be head of household in the same way as a man (1=yes; 0=no)',
  'A woman can choose where to live in the same way as a man (1=yes; 0=no)',
  'A woman can get a job in the same way as a man (1=yes; 0=no)',
  'A woman can obtain a judgment of divorce in the same way as a man (1=yes; 0=no)',
  'A woman can open a bank account in the same way as a man (1=yes; 0=no)',
  'A woman can register a business in the same way as a man (1=yes; 0=no)',
  'A woman can sign a contract in the same way as a man (1=yes; 0=no)',
  'A woman can travel outside her home in the same way as a man (1=yes; 0=no)',
  'A woman can travel outside the country in the same way as a man (1=yes; 0=no)',
  'A woman can work at night in the same way as a man (1=yes; 0=no)',
  'A woman can work in a job deemed dangerous in the same way as a man (1=yes; 0=no)',
  'A woman can work in an industrial job in the same way as a man (1=yes; 0=no)',
  'A woman has the same rights to remarry as a man (1=yes; 0=no)',
  'Access to anti-retroviral drugs, female (%)',
  'Access to anti-retroviral drugs, male (%)',
  'Account ownership at a financial institution or with a mobile-money-service provider (% of population ages 15+)',
  'Account ownership at a financial institution or with a mobile-money-service provider, female (% of population ages 15+)',
  'Account ownership at a financial institution or with a mobile-money-service provider, male (% of population ages 15+)',
  'Adjusted net enrollment rate, primary (% of primary school age children)',
  'Adjusted net enrollment rate, primary, female (% of primary school age children)',
  'Adjusted net enrollment rate, primary, male (% of primary school age children)',
  'Adolescent fertility rate (births per 1,000 women ages 15-19)',
  'Age at first marriage, female',
  'Age at first marriage, male',
  'Births attended by skilled health staff (% of total)',
  'Borrowed any money in the past year (% age 15+)',
  'Borrowed any money in the past year, female (% age 15+)',
  'Borrowed any money in the past year, male  (% age 15+)',
  'Borrowed for education or school fees (% age 15+)',
  'Borrowed for education or school fees, female  (% age 15+)',
  'Borrowed for education or school fees, male  (% age 15+)',
  'Borrowed for health or medical purposes (% age 15+)',
  'Borrowed for health or medical purposes, female  (% age 15+)',
  'Borrowed for health or medical purposes, male  (% age 15+)',
  'Borrowed from a financial institution (% age 15+)',
  'Borrowed from a financial institution or used a credit card (% age 15+)',
  'Borrowed from a financial institution or used a credit card, female (% age 15+)',
  'Borrowed from a financial institution or used a credit card, male (% age 15+)',
  'Borrowed from a financial institution, female (% age 15+)',
  'Borrowed from a financial institution, male (% age 15+)',
  'Borrowed from a store by buying on credit (% age 15+)',
  'Borrowed from a store by buying on credit, female (% age 15+)',
  'Borrowed from a store by buying on credit, male (% age 15+)',
  'Borrowed from family or friends (% age 15+)',
  'Borrowed from family or friends, female (% age 15+)',
  'Borrowed from family or friends, male  (% age 15+)',
  'Borrowed to start, operate, or expand a farm or business (% age 15+)',
  'Borrowed to start, operate, or expand a farm or business, female (% age 15+)',
  'Borrowed to start, operate, or expand a farm or business, male (% age 15+)',
  'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions (% of total)',
  'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions, ages 0-4 (% of population ages 0-4)',
  'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions, ages 0-4, female (% of female population ages 0-4)',
  'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions, ages 0-4, male (% of male population ages 0-4)',
  'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions, ages 15-59 (% of population ages 15-59)',
  'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions, ages 15-59, female (% of female population ages 15-59)',
  'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions, ages 15-59, male (% of male population ages 15-59)',
  'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions, ages 5-14 (% of population ages 5-14)',
  'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions, ages 5-14, female (% of female population ages 5-14)',
  'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions, ages 5-14, male (% of male population ages 5-14)',
  'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions, ages 60+ (% of population ages 60+)',
  'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions, ages 60+, female (% of female population ages 60+)',
  'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions, ages 60+, male (% of male population ages 60+)',
  'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions, female (% of female population)',
  'Cause of death, by communicable diseases and maternal, prenatal and nutrition conditions, male (% of male population)',
  'Cause of death, by injury (% of total)',
  'Cause of death, by injury, ages 0-4 (% of population ages 0-4)',
  'Cause of death, by injury, ages 0-4, female (% of female population ages 0-4)',
  'Cause of death, by injury, ages 0-4, male (% of male population ages 0-4)',
  'Cause of death, by injury, ages 15-59 (% of population ages 15-59)',
  'Cause of death, by injury, ages 15-59, female (% of female population ages 15-59)',
  'Cause of death, by injury, ages 15-59, male (% of male population ages 15-59)',
  'Cause of death, by injury, ages 5-14 (% of population ages 5-14)',
  'Cause of death, by injury, ages 5-14, female (% of female population ages 5-14)',
  'Cause of death, by injury, ages 5-14, male (% of male population ages 5-14)',
  'Cause of death, by injury, ages 60+ (% of population ages 60+)',
  'Cause of death, by injury, ages 60+, female (% of female population ages 60+)',
  'Cause of death, by injury, ages 60+, male (% of male population ages 60+)',
  'Cause of death, by injury, female (% of female population)',
  'Cause of death, by injury, male (% of male population)',
  'Cause of death, by non-communicable diseases (% of total)',
  'Cause of death, by non-communicable diseases, ages 0-4 (% of population ages 0-4)',
  'Cause of death, by non-communicable diseases, ages 0-4, female (% of female population ages 0-4)',
  'Cause of death, by non-communicable diseases, ages 0-4, male (% of male population ages 0-4)',
  'Cause of death, by non-communicable diseases, ages 15-59 (% of population ages 15-59)',
  'Cause of death, by non-communicable diseases, ages 15-59, female (% of female population ages 15-59)',
  'Cause of death, by non-communicable diseases, ages 15-59, male (% of male population ages 15-59)',
  'Cause of death, by non-communicable diseases, ages 5-14 (% of population ages 5-14)',
  'Cause of death, by non-communicable diseases, ages 5-14, female (% of female population ages 5-14)',
  'Cause of death, by non-communicable diseases, ages 5-14, male (% of male population ages 5-14)',
  'Cause of death, by non-communicable diseases, ages 60+ (% of population ages 60+)',
  'Cause of death, by non-communicable diseases, ages 60+, female (% of female population ages 60+)',
  'Cause of death, by non-communicable diseases, ages 60+, male (% of male population ages 60+)',
  'Cause of death, by non-communicable diseases, female (% of female population)',
  'Cause of death, by non-communicable diseases, male (% of male population)',
  'Children in employment, female (% of female children ages 7-14)',
  'Children in employment, male (% of male children ages 7-14)',
  'Children in employment, total (% of children ages 7-14)',
  'Children out of school (% of primary school age)',
  'Children out of school, primary',
  'Children out of school, primary, female',
  'Children out of school, primary, male',
  'Coming up with emergency funds: not possible (% age 15+)',
  'Coming up with emergency funds: not possible, female  (% age 15+)',
  'Coming up with emergency funds: not possible, male (% age 15+)',
  'Coming up with emergency funds: possible (% age 15+)',
  'Coming up with emergency funds: possible, female (% age 15+)',
  'Coming up with emergency funds: possible, male (% age 15+)',
  'Contraceptive prevalence, any methods (% of women ages 15-49)',
  'Contraceptive prevalence, modern methods (% of women ages 15-49)',
  'Cost of business start-up procedures (% of GNI per capita)',
  'Cost of business start-up procedures, female (% of GNI per capita)',
  'Cost of business start-up procedures, male (% of GNI per capita)',
  'Credit card ownership (% age 15+)',
  'Credit card ownership, female  (% age 15+)',
  'Credit card ownership, male (% age 15+)',
  'Criminal penalties or civil remedies exist for sexual harassment in employment (1=yes; 0=no)',
  'Debit card ownership (% age 15+)',
  'Debit card ownership, female (% age 15+)',
  'Debit card ownership, male  (% age 15+)',
  'Demand for family planning satisfied by modern methods (% of married women with demand for family planning)',
  'Dismissal of pregnant workers is prohibited (1=yes; 0=no)',
  'Educational attainment, at least completed lower secondary, population 25+, female (%) (cumulative)',
  'Educational attainment, at least completed lower secondary, population 25+, male (%) (cumulative)',
  'Educational attainment, at least completed lower secondary, population 25+, total (%) (cumulative)',
  'Educational attainment, at least completed post-secondary, population 25+, female (%) (cumulative)',
  'Educational attainment, at least completed post-secondary, population 25+, male (%) (cumulative)',
  'Educational attainment, at least completed post-secondary, population 25+, total (%) (cumulative)',
  'Educational attainment, at least completed upper secondary, population 25+, female (%) (cumulative)',
  'Educational attainment, at least completed upper secondary, population 25+, male (%) (cumulative)',
  'Educational attainment, at least completed upper secondary, population 25+, total (%) (cumulative)',
  'Educational attainment, Doctoral or equivalent, population 25+, total (%) (cumulative)',
  'Employers, female (% of female employment) (modeled ILO estimate)',
  'Employers, male (% of male employment) (modeled ILO estimate)',
  'Employers, total (% of total employment) (modeled ILO estimate)',
  'Employment in agriculture (% of total employment) (modeled ILO estimate)',
  'Employment in agriculture, female (% of female employment) (modeled ILO estimate)',
  'Employment in agriculture, male (% of male employment) (modeled ILO estimate)',
  'Employment in industry (% of total employment) (modeled ILO estimate)',
  'Employment in industry, female (% of female employment) (modeled ILO estimate)',
  'Employment in industry, male (% of male employment) (modeled ILO estimate)',
  'Employment in services (% of total employment) (modeled ILO estimate)',
  'Employment in services, female (% of female employment) (modeled ILO estimate)',
  'Employment in services, male (% of male employment) (modeled ILO estimate)',
  'Employment to population ratio, 15+, female (%) (modeled ILO estimate)',
  'Employment to population ratio, 15+, female (%) (national estimate)',
  'Employment to population ratio, 15+, male (%) (modeled ILO estimate)',
  'Employment to population ratio, 15+, male (%) (national estimate)',
  'Employment to population ratio, 15+, total (%) (modeled ILO estimate)',
  'Employment to population ratio, 15+, total (%) (national estimate)',
  'Employment to population ratio, ages 15-24, female (%) (modeled ILO estimate)',
  'Employment to population ratio, ages 15-24, female (%) (national estimate)',
  'Employment to population ratio, ages 15-24, male (%) (modeled ILO estimate)',
  'Employment to population ratio, ages 15-24, male (%) (national estimate)',
  'Employment to population ratio, ages 15-24, total (%) (modeled ILO estimate)',
  'Employment to population ratio, ages 15-24, total (%) (national estimate)',
  'Expected Years of School',
  'Expected Years of School, Female',
  'Expected Years of School, Male',
  'Expected years of schooling',
  'Expected years of schooling, female',
  'Expected years of schooling, male',
  'Female and male surviving spouses have equal rights to inherit assets (1=yes; 0=no)',
  'Female genital mutilation prevalence (%)',
  'Female genital mutilation prevalence (%): Q1 (lowest)',
  'Female genital mutilation prevalence (%): Q2',
  'Female genital mutilation prevalence (%): Q3',
  'Female genital mutilation prevalence (%): Q4',
  'Female genital mutilation prevalence (%): Q5 (highest)',
  'Female share of graduates from Science, Technology, Engineering and Mathematics (STEM) programmes, tertiary (%)',
  'Female share of graduates in Agriculture, Forestry, Fisheries and Veterinary programmes, tertiary (%)',
  'Female share of graduates in Arts and Humanities programmes, tertiary (%)',
  'Female share of graduates in Business, Administration and Law programmes, tertiary (%)',
  'Female share of graduates in Education programmes, tertiary (%)',
  'Female share of graduates in Engineering, Manufacturing and Construction programmes, tertiary (%)',
  'Female share of graduates in Health and Welfare programmes, tertiary (%)',
  'Female share of graduates in Information and Communication Technologies programmes, tertiary (%)',
  'Female share of graduates in Natural Sciences, Mathematics and Statistics programmes, tertiary (%)',
  'Female share of graduates in other fields than Science, Technology, Engineering and Mathematics programmes, tertiary (%)',
  'Female share of graduates in Services programmes, tertiary (%)',
  'Female share of graduates in Social Sciences, Journalism and Information programmes, tertiary (%)',
  'Female share of graduates in unknown or unspecified fields, tertiary (%)',
  'Fertility rate, total (births per woman)',
  'Financial institution account (% age 15+)',
  'Financial institution account,female(% age 15+)',
  'Financial institution account,male(% age 15+)',
  'Firms with female participation in ownership (% of firms)',
  'Firms with female top manager (% of firms)',
  'Fraction of Children Under 5 Not Stunted',
  'Fraction of Children Under 5 Not Stunted, Female',
  'Fraction of Children Under 5 Not Stunted, Male',
  'GDP per capita (constant 2010 US\$)',
  'Gross graduation ratio, primary, female (%)',
  'Gross graduation ratio, primary, male (%)',
  'Gross graduation ratio, primary, total (%)',
  'Gross graduation ratio, tertiary, female (%)',
  'Gross graduation ratio, tertiary, male (%)',
  'Gross graduation ratio, tertiary, total (%)',
  'Gross intake ratio in first grade of primary education, total (% of relevant age group)',
  'Harmonized Test Scores',
  'Harmonized Test Scores, Female',
  'Harmonized Test Scores, Male',
  'Immunization, DPT (% of children ages 12-23 months)',
  'Immunization, measles (% of children ages 12-23 months)',
  'Incidence of HIV, ages 15-24 (per 1,000 uninfected population ages 15-24)',
  'Incidence of HIV, ages 15-24, female (per 1,000 uninfected female population ages 15-24)',
  'Incidence of HIV, ages 15-24, male (per 1,000 uninfected male population ages 15-24)',
  'Incidence of HIV, ages 15-49 (per 1,000 uninfected population ages 15-49)',
  'Incidence of HIV, ages 15-49, female (per 1,000 uninfected female population ages 15-49)',
  'Incidence of HIV, ages 15-49, male (per 1,000 uninfected male population ages 15-49)',
  'Informal employment, female (% of total non-agricultural employment)',
  'Informal employment, male (% of total non-agricultural employment)',
  'Intentional homicides (per 100,000 people)',
  'Labor force participation rate for ages 15-24, female (%) (modeled ILO estimate)',
  'Labor force participation rate for ages 15-24, female (%) (national estimate)',
  'Labor force participation rate for ages 15-24, male (%) (modeled ILO estimate)',
  'Labor force participation rate for ages 15-24, male (%) (national estimate)',
  'Labor force participation rate for ages 15-24, total (%) (modeled ILO estimate)',
  'Labor force participation rate for ages 15-24, total (%) (national estimate)',
  'Labor force participation rate, female (% of female population ages 15+) (modeled ILO estimate)',
  'Labor force participation rate, female (% of female population ages 15+) (national estimate)',
  'Labor force participation rate, female (% of female population ages 15-64) (modeled ILO estimate)',
  'Labor force participation rate, male (% of male population ages 15+) (modeled ILO estimate)',
  'Labor force participation rate, male (% of male population ages 15+) (national estimate)',
  'Labor force participation rate, male (% of male population ages 15-64) (modeled ILO estimate)',
  'Labor force participation rate, total (% of total population ages 15+) (modeled ILO estimate)',
  'Labor force participation rate, total (% of total population ages 15+) (national estimate)',
  'Labor force participation rate, total (% of total population ages 15-64) (modeled ILO estimate)',
  'Labor force with advanced education (% of total working-age population with advanced education)',
  'Labor force with advanced education, female (% of female working-age population with advanced education)',
  'Labor force with advanced education, male (% of male working-age population with advanced education)',
  'Labor force with basic education (% of total working-age population with basic education)',
  'Labor force with basic education, female (% of female working-age population with basic education)',
  'Labor force with basic education, male (% of male working-age population with basic education)',
  'Labor force with intermediate education (% of total working-age population with intermediate education)',
  'Labor force with intermediate education, female (% of female working-age population with intermediate education)',
  'Labor force with intermediate education, male (% of male working-age population with intermediate education)',
  'Labor force, female',
  'Labor force, female (% of total labor force)',
  'Labor force, male',
  'Labor force, total',
  'Law mandates equal remuneration for females and males for work of equal value (1=yes; 0=no)',
  'Law prohibits discrimination in employment based on gender (1=yes; 0=no)',
  'Learning-Adjusted Years of School',
  'Learning-Adjusted Years of School, Female',
  'Learning-Adjusted Years of School, Male',
  'Length of paid maternity leave (calendar days)',
  'Length of paid parental leave for father (calendar days)',
  'Length of paid parental leave for mother (calendar days)',
  'Length of paid paternity leave (calendar days)',
  'Length of paid shared parental leave (calendar days)',
  'Literacy rate, adult female (% of females ages 15 and above)',
  'Literacy rate, adult male (% of males ages 15 and above)',
  'Literacy rate, adult total (% of people ages 15 and above)',
  'Literacy rate, youth (ages 15-24), gender parity index (GPI)',
  'Literacy rate, youth female (% of females ages 15-24)',
  'Literacy rate, youth male (% of males ages 15-24)',
  'Literacy rate, youth total (% of people ages 15-24)',
  'Lower secondary completion rate, female (% of relevant age group)',
  'Lower secondary completion rate, male (% of relevant age group)',
  'Lower secondary completion rate, total (% of relevant age group)',
  'Made digital payments in the past year (% age 15+)',
  'Made digital payments in the past year, female  (% age 15+)',
  'Made digital payments in the past year, male  (% age 15+)',
  'Made or received digital payments in the past year (% age 15+)',
  'Made or received digital payments in the past year, female  (% age 15+)',
  'Made or received digital payments in the past year, male  (% age 15+)',
  'Main source of emergency funds: family or friends (% able to raise funds, age 15+)',
  'Main source of emergency funds: family or friends, female  (% able to raise funds, age 15+)',
  'Main source of emergency funds: family or friends, male  (% able to raise funds, age 15+)',
  'Main source of emergency funds: savings (% able to raise funds, age 15+)',
  'Main source of emergency funds: savings, female (% able to raise funds, age 15+)',
  'Main source of emergency funds: savings, male  (% able to raise funds, age 15+)',
  'Mandatory retirement age, female',
  'Mandatory retirement age, male',
  'Maternal mortality ratio (modeled estimate, per 100,000 live births)',
  'Men and married women have equal ownership rights to immovable property (1=yes; 0=no)',
  'Mortality caused by road traffic injury (per 100,000 population)',
  'Mortality caused by road traffic injury, female (per 100,000 female population)',
  'Mortality caused by road traffic injury, male (per 100,000 male population)',
  'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70 (%)',
  'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70, female (%)',
  'Mortality from CVD, cancer, diabetes or CRD between exact ages 30 and 70, male (%)',
  'Mortality rate attributed to household and ambient air pollution, age-standardized (per 100,000 population)',
  'Mortality rate attributed to household and ambient air pollution, age-standardized, female (per 100,000 female population)',
  'Mortality rate attributed to household and ambient air pollution, age-standardized, male (per 100,000 male population)',
  'Mortality rate attributed to unintentional poisoning (per 100,000 population)',
  'Mortality rate attributed to unintentional poisoning, female (per 100,000 female population)',
  'Mortality rate attributed to unintentional poisoning, male (per 100,000 male population)',
  'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene (per 100,000 population)',
  'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene, female (per 100,000 female population)',
  'Mortality rate attributed to unsafe water, unsafe sanitation and lack of hygiene, male (per 100,000 male population)',
  'Mortality rate, infant (per 1,000 live births)',
  'Mortality rate, infant, female (per 1,000 live births)',
  'Mortality rate, infant, male (per 1,000 live births)',
  'Mortality rate, under-5 (per 1,000 live births)',
  'Mortality rate, under-5, female (per 1,000 live births)',
  'Mortality rate, under-5, male (per 1,000 live births)',
  'No deposit and no withdrawal from an account in the past year (% age 15+)',
  'No deposit and no withdrawal from an account in the past year, male  (% age 15+)',
  'Number of infant deaths',
  'Number of infant deaths, female',
  'Number of infant deaths, male',
  'Number of maternal deaths',
  'Number of under-five deaths, female',
  'Number of under-five deaths, male',
  'Outstanding housing loan (% age 15+)',
  'Outstanding housing loan, female (% age 15+)',
  'Outstanding housing loan, male  (% age 15+)',
  'Outstanding loan for a funeral or wedding (% age 15+)',
  'Outstanding loan for a funeral or wedding, female (% age 15+)',
  'Outstanding loan for a funeral or wedding, male (% age 15+)',
  'Paid leave is available to fathers (1=yes; 0=no)',
  'Paid leave of at least 14 weeks available to mothers (1=yes; 0=no)',
  'Paid school fees in the past year (% age 15+)',
  'Paid school fees in the past year, female  (% age 15+)',
  'Paid school fees in the past year, male (% age 15+)',
  'Paid utility bills in the past year (% age 15+)',
  'Paid utility bills in the past year, female (% age 15+)',
  'Paid utility bills in the past year, male (% age 15+)',
  'People practicing open defecation (% of population)',
  'People practicing open defecation, rural (% of rural population)',
  'People practicing open defecation, urban (% of urban population)',
  'Percentage of students in upper secondary vocational education who are female (%)',
  'Persistence to grade 5, female (% of cohort)',
  'Persistence to grade 5, male (% of cohort)',
  'Pregnant women receiving prenatal care (%)',
  'Prevalence of anemia among women of reproductive age (% of women ages 15-49)',
  'Prevalence of HIV, female (% ages 15-24)',
  'Prevalence of HIV, male (% ages 15-24)',
  'Prevalence of overweight, weight for height (% of children under 5)',
  'Prevalence of overweight, weight for height, female (% of children under 5)',
  'Prevalence of overweight, weight for height, male (% of children under 5)',
  'Prevalence of severe wasting, weight for height (% of children under 5)',
  'Prevalence of severe wasting, weight for height, female (% of children under 5)',
  'Prevalence of severe wasting, weight for height, male (% of children under 5)',
  'Prevalence of stunting, height for age (% of children under 5)',
  'Prevalence of stunting, height for age, female (% of children under 5)',
  'Prevalence of stunting, height for age, male (% of children under 5)',
  'Prevalence of underweight, weight for age (% of children under 5)',
  'Prevalence of underweight, weight for age, female (% of children under 5)',
  'Prevalence of underweight, weight for age, male (% of children under 5)',
  'Prevalence of wasting, weight for height (% of children under 5)',
  'Prevalence of wasting, weight for height, female (% of children under 5)',
  'Prevalence of wasting, weight for height, male (% of children under 5)',
  'Primary completion rate, female (% of relevant age group)',
  'Primary completion rate, male (% of relevant age group)',
  'Primary completion rate, total (% of relevant age group)',
  'Primary education, pupils (% female)',
  'Primary education, teachers (% female)',
  'Probability of Survival to Age 5',
  'Probability of Survival to Age 5, Female',
  'Probability of Survival to Age 5, Male',
  'Progression to secondary school (%)',
  'Progression to secondary school, female (%)',
  'Progression to secondary school, male (%)',
  'Proportion of seats held by women in national parliaments (%)',
  'Proportion of women in ministerial level positions (%)',
  'Rate of out-of-school youth of upper secondary school age, female (%)',
  'Rate of out-of-school youth of upper secondary school age, male (%)',
  'Ratio of female to male labor force participation rate (%) (national estimate)',
  'Ratio of female to male youth unemployment rate (% ages 15-24) (modeled ILO estimate)',
  'Ratio of female to male youth unemployment rate (%) (national estimate)',
  'Received digital payments in the past year (% age 15+)',
  'Received digital payments in the past year, female  (% age 15+)',
  'Received digital payments in the past year, male (% age 15+)',
  'Received domestic remittances in the past year (% age 15+)',
  'Received domestic remittances in the past year, female (% age 15+)',
  'Received domestic remittances in the past year, male  (% age 15+)',
  'Received government payments in the past year (% age 15+)',
  'Received government payments in the past year, female (% age 15+)',
  'Received government payments in the past year, male (% age 15+)',
  'Received government transfers in the past year (% age 15+)',
  'Received government transfers in the past year, female (% age 15+)',
  'Received government transfers in the past year, male  (% age 15+)',
  'Retirement age with full benefits, female',
  'Retirement age with full benefits, male',
  'Retirement age with partial benefits, female',
  'Retirement age with partial benefits, male',
  'Saved any money in the past year (% age 15+)',
  'Saved any money in the past year, female  (% age 15+)',
  'Saved any money in the past year, male  (% age 15+)',
  'Saved at a financial institution (% age 15+)',
  'Saved at a financial institution, female (% age 15+)',
  'Saved at a financial institution, male (% age 15+)',
  'Saved for education or school fees (% age 15+)',
  'Saved for education or school fees, female  (% age 15+)',
  'Saved for education or school fees, male (% age 15+)',
  'Saved for old age (% age 15+)',
  'Saved for old age, female (% age 15+)',
  'Saved for old age, male (% age 15+)',
  'Saved to start, operate, or expand a farm or business (% age 15+)',
  'Saved to start, operate, or expand a farm or business, female (% age 15+)',
  'Saved to start, operate, or expand a farm or business, male (% age 15+)',
  'Saved using a savings club or a person outside the family (% age 15+)',
  'Saved using a savings club or a person outside the family, female (% age 15+)',
  'Saved using a savings club or a person outside the family, male (% age 15+)',
  'School enrollment, preprimary (% gross)',
  'School enrollment, preprimary, female (% gross)',
  'School enrollment, preprimary, male (% gross)',
  'School enrollment, primary (% gross)',
  'School enrollment, primary (% net)',
  'School enrollment, primary (gross), gender parity index (GPI)',
  'School enrollment, primary and secondary (gross), gender parity index (GPI)',
  'School enrollment, primary, female (% gross)',
  'School enrollment, primary, female (% net)',
  'School enrollment, primary, male (% gross)',
  'School enrollment, primary, male (% net)',
  'School enrollment, secondary (% gross)',
  'School enrollment, secondary (% net)',
  'School enrollment, secondary (gross), gender parity index (GPI)',
  'School enrollment, secondary, female (% gross)',
  'School enrollment, secondary, female (% net)',
  'School enrollment, secondary, male (% gross)',
  'School enrollment, secondary, male (% net)',
  'School enrollment, tertiary (% gross)',
  'School enrollment, tertiary (gross), gender parity index (GPI)',
  'School enrollment, tertiary, female (% gross)',
  'School enrollment, tertiary, male (% gross)',
  'Secondary education, pupils (% female)',
  'Secondary education, teachers (% female)',
  'Secondary education, vocational pupils',
  'Secondary education, vocational pupils (% female)',
  'Self-employed, female (% of female employment) (modeled ILO estimate)',
  'Self-employed, male (% of male employment) (modeled ILO estimate)',
  'Self-employed, total (% of total employment) (modeled ILO estimate)',
  'Sent domestic remittances in the past year (% age 15+)',
  'Sent domestic remittances in the past year, female  (% age 15+)',
  'Sent domestic remittances in the past year, male (% age 15+)',
  'Sent or received domestic remittances in the past year (% age 15+)',
  'Sent or received domestic remittances in the past year, female (% age 15+)',
  'Sent or received domestic remittances in the past year, male (% age 15+)',
  'Share of all students in upper secondary education enrolled in vocational programmes (%)',
  'Share of female students in upper secondary education enrolled in vocational programmes (%)',
  'Share of male students in secondary education enrolled in vocational programmes (%)',
  'Share of male students in upper secondary education enrolled in vocational programmes (%)',
  'Share of youth not in education, employment or training, female (% of female youth population)',
  'Share of youth not in education, employment or training, male (% of male youth population)',
  'Share of youth not in education, employment or training, total (% of youth population)',
  'Sons and daughters have equal rights to inherit assets from their parents (1=yes; 0=no)',
  'Start-up procedures to register a business (number)',
  'Start-up procedures to register a business, female (number)',
  'Start-up procedures to register a business, male (number)',
  'Suicide mortality rate (per 100,000 population)',
  'Suicide mortality rate, female (per 100,000 female population)',
  'Suicide mortality rate, male (per 100,000 male population)',
  'Survival Rate from Age 15-60',
  'Survival Rate from Age 15-60, Female',
  'Survival Rate from Age 15-60, Male',
  'Tertiary education, academic staff (% female)',
  'The age at which men and women can retire with full pension benefits is the same (1=yes; 0=no)',
  'The age at which men and women can retire with partial pension benefits is the same (1=yes; 0=no)',
  'The government administers 100% of maternity leave benefits (1=yes; 0=no)',
  'The law grants spouses equal administrative authority over assets during marriage (1=yes; 0=no)',
  'The law prohibits discrimination in access to credit based on gender (1=yes; 0=no)',
  'The law provides for the valuation of nonmonetary contributions (1=yes; 0=no)',
  'The mandatory retirement age for men and women is the same (1=yes; 0=no)',
  'There are periods of absence due to child care accounted for in pension benefits (1=yes; 0=no)',
  'There is legislation on sexual harassment in employment (1=yes; 0=no)',
  'There is legislation specifically addressing domestic violence (1=yes; 0=no)',
  'There is no legal provision that requires a married woman to obey her husband (1=yes; 0=no)',
  'There is paid parental leave (1=yes; 0=no)',
  'Time required to start a business (days)',
  'Time required to start a business, female (days)',
  'Time required to start a business, male (days)',
  'Total alcohol consumption per capita (liters of pure alcohol, projected estimates, 15+ years of age)',
  'Total alcohol consumption per capita, female (liters of pure alcohol, projected estimates, female 15+ years of age)',
  'Total alcohol consumption per capita, male (liters of pure alcohol, projected estimates, male 15+ years of age)',
  'Unemployment with advanced education (% of total labor force with advanced education)',
  'Unemployment with advanced education, female (% of female labor force with advanced education)',
  'Unemployment with advanced education, male (% of male labor force with advanced education)',
  'Unemployment with basic education (% of total labor force with basic education)',
  'Unemployment with basic education, female (% of female labor force with basic education)',
  'Unemployment with basic education, male (% of male labor force with basic education)',
  'Unemployment with intermediate education (% of total labor force with intermediate education)',
  'Unemployment with intermediate education, female (% of female labor force with intermediate education)',
  'Unemployment with intermediate education, male (% of male labor force with intermediate education)',
  'Unemployment, female (% of female labor force) (modeled ILO estimate)',
  'Unemployment, female (% of female labor force) (national estimate)',
  'Unemployment, male (% of male labor force) (modeled ILO estimate)',
  'Unemployment, male (% of male labor force) (national estimate)',
  'Unemployment, total (% of total labor force) (modeled ILO estimate)',
  'Unemployment, total (% of total labor force) (national estimate)',
  'Unemployment, youth female (% of female labor force ages 15-24) (modeled ILO estimate)',
  'Unemployment, youth female (% of female labor force ages 15-24) (national estimate)',
  'Unemployment, youth male (% of male labor force ages 15-24) (modeled ILO estimate)',
  'Unemployment, youth male (% of male labor force ages 15-24) (national estimate)',
  'Unemployment, youth total (% of total labor force ages 15-24) (modeled ILO estimate)',
  'Unemployment, youth total (% of total labor force ages 15-24) (national estimate)',
  'Unmet need for contraception (% of married women ages 15-49)',
  'Used the internet to pay bills or to buy something online in the past year (% age 15+)',
  'Used the internet to pay bills or to buy something online in the past year, female (% age 15+)',
  'Used the internet to pay bills or to buy something online in the past year, male (% age 15+)',
  'Vocational and Technical enrolment (% of total secondary enrolment), female',
  'Vocational and Technical enrolment (% of total secondary enrolment), total',
  'Vulnerable employment, female (% of female employment) (modeled ILO estimate)',
  'Vulnerable employment, male (% of male employment) (modeled ILO estimate)',
  'Vulnerable employment, total (% of total employment) (modeled ILO estimate)',
  'Wage and salaried workers, female (% of female employment) (modeled ILO estimate)',
  'Wage and salaried workers, male (% of male employment) (modeled ILO estimate)',
  'Wage and salaried workers, total (% of total employment) (modeled ILO estimate)',
  'Wanted fertility rate (births per woman)',
  'Women Business and the Law Index Score (scale 1-100)',
  'Women who believe a husband is justified in beating his wife (any of five reasons) (%)',
  'Women who were first married by age 15 (% of women ages 20-24)',
  'Women who were first married by age 18 (% of women ages 20-24)',
  'Women\'s share of population ages 15+ living with HIV (%)',
  'Youth illiterate population, 15-24 years, % female',
  'Youth illiterate population, 15-24 years, both sexes (number)',
  'Youth illiterate population, 15-24 years, female (number)',
  'Youth illiterate population, 15-24 years, male (number)'
];

List<String> healthIndicators = [];

List<String> infrastructureIndicators = [
  'Air transport, freight (million ton-km)',
  'Air transport, passengers carried',
  'Air transport, registered carrier departures worldwide',
  'Container port traffic (TEU: 20 foot equivalent units)',
  'Fixed broadband subscriptions',
  'Fixed broadband subscriptions (per 100 people)',
  'Fixed telephone subscriptions',
  'Fixed telephone subscriptions (per 100 people)',
  'High-technology exports (% of manufactured exports)',
  'High-technology exports (current US\$)',
  'ICT goods exports (% of total goods exports)',
  'ICT goods imports (% total goods imports)',
  'ICT service exports (% of service exports, BoP)',
  'ICT service exports (BoP, current US\$)',
  'Individuals using the Internet (% of population)',
  'Industrial design applications, nonresident, by count',
  'Industrial design applications, resident, by count',
  'Liner shipping connectivity index (maximum value in 2004 = 100)',
  'Mobile cellular subscriptions',
  'Mobile cellular subscriptions (per 100 people)',
  'Patent applications, nonresidents',
  'Patent applications, residents',
  'Pump price for diesel fuel (US\$ per liter)',
  'Pump price for gasoline (US\$ per liter)',
  'Rail lines (total route-km)',
  'Railways, goods transported (million ton-km)',
  'Railways, passengers carried (million passenger-km)',
  'Research and development expenditure (% of GDP)',
  'Researchers in R&D (per million people)',
  'Scientific and technical journal articles',
  'Secure Internet servers',
  'Secure Internet servers (per 1 million people)',
  'Technicians in R&D (per million people)',
  'Trademark applications, direct nonresident',
  'Trademark applications, direct resident',
  'Trademark applications, nonresident, by count',
  'Trademark applications, resident, by count',
  'Trademark applications, total'
];

List<String> populationIndicators = [
  "Total Population",
  "Male Population",
  "Female Population",
];

List<String> povertyIndicators = [
  'Gini index (World Bank estimate)',
  'Income share held by fourth 20%',
  'Income share held by highest 10%',
  'Income share held by highest 20%',
  'Income share held by lowest 10%',
  'Income share held by lowest 20%',
  'Income share held by second 20%',
  'Income share held by third 20%',
  'Multidimensional poverty, Drinking water (% of population deprived)',
  'Multidimensional poverty, Educational attainment (% of population deprived)',
  'Multidimensional poverty, Educational enrollment (% of population deprived)',
  'Multidimensional poverty, Electricity (% of population deprived)',
  'Multidimensional poverty, Headcount ratio (% of population)',
  'Multidimensional poverty, Monetary poverty (% of population deprived)',
  'Multidimensional poverty, Sanitation (% of population deprived)',
  'Number of poor at \$1.90 a day (2011 PPP) (millions)',
  'Number of poor at \$3.10 a day (2011 PPP) (millions)',
  'Number of poor at \$3.20 a day (2011 PPP) (millions)',
  'Number of poor at \$5.50 a day (2011 PPP) (millions)',
  'Poverty gap at \$1.90 a day (2011 PPP) (%)',
  'Poverty gap at \$3.10 a day (2011 PPP) (%)',
  'Poverty gap at \$3.20 a day (2011 PPP) (% of population)',
  'Poverty gap at \$5.50 a day (2011 PPP) (% of population)',
  'Poverty headcount ratio at \$1.90 a day (2011 PPP) (% of population)',
  'Poverty headcount ratio at \$1.90 a day, age 0-14  (2011 PPP) (% of population age 0-14)',
  'Poverty headcount ratio at \$1.90 a day, age 15-64 (2011 PPP) (% of population age 15-64)',
  'Poverty headcount ratio at \$1.90 a day, age 65+ (2011 PPP) (% of population age 65+)',
  'Poverty headcount ratio at \$1.90 a day, Female (2011 PPP) (% of female population)',
  'Poverty headcount ratio at \$1.90 a day, Male  (2011 PPP) (% of male population)',
  'Poverty headcount ratio at \$1.90 a day, rural (2011 PPP) (% of rural population)',
  'Poverty headcount ratio at \$1.90 a day, urban (2011 PPP) (% of urban population)',
  'Poverty headcount ratio at \$1.90 a day, with primary education (2011 PPP) (% of population age 16+ with primary education)',
  'Poverty headcount ratio at \$1.90 a day, with secondary education (2011 PPP) (% of population age 16+ with secondary education)',
  'Poverty headcount ratio at \$1.90 a day, without education (2011 PPP) (% of population age 16+ without education)',
  'Poverty headcount ratio at \$1.90 a day,  with Tertiary/post-secondary education (2011 PPP) (% of population age 16+ with Tertiary/post-secondary education)',
  'Poverty headcount ratio at \$3.10 a day (2011 PPP) (% of population)',
  'Poverty headcount ratio at \$3.20 a day (2011 PPP) (% of population)',
  'Poverty headcount ratio at \$5.50 a day (2011 PPP) (% of population)',
  'Poverty headcount ratio at national poverty lines (% of population)',
  'Poverty headcount ratio at national poverty lines (% of population), including noncomparable values',
  'Poverty incidence',
  'Population share',
  'Absolute contribution ',
  'Relative contribution '
];

List<MapColorMapper>? digitalAvatarMapColourMapper = [
  const MapColorMapper(
    value: "Population",
    color: Color.fromRGBO(255, 215, 0, 1.0),
    text: "Population",
  ),
  const MapColorMapper(
    color: Color.fromRGBO(72, 209, 204, 1.0),
    value: "D_E",
    text: "Democratic Transition and Economic Recovery",
  ),
  const MapColorMapper(
    color: Color.fromRGBO(171, 56, 224, 0.75),
    value: "E_E",
    text: "Energy and Environment",
  ),
  const MapColorMapper(
    color: Color.fromRGBO(126, 247, 74, 0.75),
    value: "H_D",
    text: "Health and Development",
  ),
  const MapColorMapper(
    color: Color.fromRGBO(79, 60, 201, 0.7),
    value: "I_D",
    text: "Innovation and Digitization",
  ),
  const MapColorMapper(
    color: Color.fromRGBO(99, 164, 230, 1),
    value: "P_S",
    text: "Peace and Stabilization",
  ),
  const MapColorMapper(
    color: Colors.grey,
    value: "",
    text: "No Projects",
  ),
];
