var localitiesList = [
  'Locality',
  "Abassiya",
  "Abu Hamad",
  "Abu Hujar",
  "Abu Jabrah",
  "Abu Jubayhah",
  "Abu Karinka",
  "Abu Kershola",
  "Abu Zabad",
  "Abyei",
  "Abyei PCA area",
  "Ad Dabbah",
  "Ad Dali",
  "Ad Damar",
  "Ad Dinder",
  "Ad Diwaim",
  "Ad Du'ayn",
  "Adila",
  "Ag Geneina",
  "Agig",
  "Aj Jabalain",
  "Al Buhaira",
  "Al Buram",
  "Al Burgaig",
  "Al Butanah",
  "Al Dibab",
  "Al Fao",
  "Al Fashaga",
  "Al Fasher",
  "Al Firdous",
  "Al Galabat Al Gharbyah - Kassab",
  "Al Ganab",
  "Al Gitaina",
  "Al Golid",
  "Al Hasahisa",
  "Al Idia",
  "Al Kamlin",
  "Al Khiwai",
  "Al Koma",
  "Al Kurmuk",
  "Al Lagowa",
  "Al Lait",
  "Al Leri",
  "Al Mafaza",
  "Al Malha",
  "Al Manaqil",
  "Al Matama",
  "Al Meiram",
  "Al Quoz",
  "Al Qurashi",
  "Al Qureisha",
  "Al Radoum",
  "Al Wihda",
  "An Nuhud",
  "Ar Rahad",
  "Ar Rahad",
  "Ar Rashad",
  "Ar Reif Ash Shargi",
  "Ar Rusayris",
  "As Salam - SD",
  "As Salam - WK",
  "As Salam / Ar Rawat",
  "As Serief",
  "As Suki",
  "As Sunta",
  "As Sunut",
  "Assalaya",
  "At Tadamon - BN",
  "At Tadamon - SK",
  "At Tawisha",
  "At Tina",
  "Atbara",
  "Azum",
  "Babanusa",
  "Bahr Al Arab",
  "Bahri",
  "Bara",
  "Barbar",
  "Basundah",
  "Baw",
  "Beida",
  "Beliel",
  "Bendasi",
  "Buram",
  "Damso",
  "Dar As Salam",
  "Delami",
  "Delgo",
  "Dilling",
  "Dongola",
  "Dordieb",
  "Ed Al Fursan",
  "Ed Damazine",
  "Foro Baranga",
  "Gala'a Al Nahal",
  "Galabat Ash-Shargiah",
  "Gebrat Al Sheikh",
  "Geisan",
  "Gereida",
  "Ghadeer",
  "Gharb Bara",
  "Gharb Jabal Marrah",
  "Ghubaish",
  "Guli",
  "Habila - SK",
  "Habila - WD",
  "Hala'ib",
  "Halfa",
  "Halfa Aj Jadeedah",
  "Haya",
  "Heiban",
  "Janub Aj Jazirah",
  "Jebel Awlia",
  "Jebel Moon",
  "Jubayt Elma'aadin",
  "Kadugli",
  "Karrari",
  "Kas",
  "Kateila",
  "Kebkabiya",
  "Keilak",
  "Kelemando",
  "Kereneik",
  "Kernoi",
  "Khartoum",
  "Kosti",
  "Kubum",
  "Kulbus",
  "Kutum",
  "Madeinat Al Gedaref",
  "Madeinat Kassala",
  "Medani Al Kubra",
  "Melit",
  "Mershing",
  "Merwoe",
  "Mukjar",
  "Nitega",
  "Nyala Janoub",
  "Nyala Shimal",
  "Port Sudan",
  "Rabak",
  "Rehaid Albirdi",
  "Reifi Aroma",
  "Reifi Gharb Kassala",
  "Reifi Hamashkureib",
  "Reifi Kassla",
  "Reifi Khashm Elgirba",
  "Reifi Nahr Atbara",
  "Reifi Shamal Ad Delta",
  "Reifi Telkok",
  "Reifi Wad Elhilaiw",
  "Saraf Omra",
  "Sawakin",
  "Sennar",
  "Shamal Jabal Marrah",
  "Sharg Aj Jabal",
  "Sharg Aj Jazirah",
  "Sharg An Neel",
  "Sharg Sennar",
  "Shattaya",
  "Sheikan",
  "Shendi",
  "Shia'ria",
  "Sinja",
  "Sinkat",
  "Sirba",
  "Soudari",
  "Talawdi",
  "Tawila",
  "Tawkar",
  "Tendalti",
  "Tulus",
  "Um Algura",
  "Um Bada",
  "Um Baru",
  "Um Dafoug",
  "Um Dam Haj Ahmed",
  "Um Dukhun",
  "Um Durein",
  "Um Durman",
  "Um Kadadah",
  "Um Rawaba",
  "Um Rimta",
  "Wad Al Mahi",
  "Wad Bandah",
  "Wadi Salih",
  "Wasat Al Gedaref",
  "Wasat Jabal Marrah",
  "Yassin",
  "Zalingi"
];

var cityList = [
  'City',
  "Abekr",
  "Abyei",
  "Al Fasher",
  "Al Managil",
  "Al Gedaref",
  "Atbara",
  "Babanusa",
  "Berber",
  "Buwaidhaa",
  "Delgo",
  "Dongola",
  "Ad-Damazin",
  "Ed Dueim",
  "El Ait",
  "El Gebir",
  "En Nahud",
  "El-Obeid",
  "Er Rahad",
  "Geneina",
  "Hala'ib",
  "`Iyāl Bakhīt",
  "Kaduqli",
  "Kassala",
  "Kauda",
  "Khartoum",
  "Bahri",
  "Kosti",
  "Merowe",
  "Muglad",
  "Nebelat el Hagana",
  "Halfa Aljadeda",
  "Nyala",
  "Omdurman",
  "Port Sudan",
  "Rabak",
  "Umm Rawaba",
  "Sennar",
  "Shendi",
  "Sindscha",
  "Singa",
  "Suakin",
  "Tabat",
  "Al Shaikh Abdulmahmood",
  "Taiyara",
  "Tonj",
  "Wad Banda",
  "Wad Medani",
  "Wadi Halfa",
  "Umm Badr",
  "Umm Bel",
  "Umm Dam",
  "Umm Debbi",
  "Umm Gafala",
  "Umm Keddada",
  "Umm Qantur",
  "Um Rawaba",
  "Umm Saiyala",
  "Umm Shanqa",
];

var stateList = [
  'State',
  "Khartoum",
  "North Kordofan",
  "Northern",
  "Kassala",
  "Blue Nile",
  "North Darfur",
  "South Darfur",
  "South Kordofan",
  "Aj Jazirah",
  "White Nile",
  "River Nile",
  "Red Sea",
  "Gedaref",
  "Sennar",
  "West Darfur",
  "Central Darfur",
  "East Darfur",
  "West Kordofan",
];

var provincesList = [
  "Province",
  "Abyei",
  "Sinnar",
  "Blue Nile",
  "West Darfur",
  "East Darfur",
  "Kassala",
  "Khartoum",
  "Merowe",
  "Jibal El Nouba",
];

var regionsList = [
  'Region',
  "Central Sudan",
  "Kordofan",
  "Northern Sudan",
  "Darfur",
  "Eastern Sudan",
];